version: "3.8"

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4000
    networks:
      - app-network
    ports:
      - "4000:4000"

networks:
  app-network:
    driver: bridge