version: "3.8"

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    ports: 
      - '80:8081' 

networks:
  app-network:
    driver: bridge